### ISSUE TITLE
[question]: SSO session token expiration

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#100]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

How can I increase the expiration for the my users sso session?

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Every SSO connection has its own expiration timing. What in particular are you looking to increase?

**Comment by wesbragagt** [comment]
> Every SSO connection has its own expiration timing. What in particular are you looking to increase?

I'm looking to increase the total session expiration from what it seems to be 8 hours to 12 hours.

**Comment by fullykubed** [comment]
Every discrete system (AWS, vault, kubernetes, etc.) has its own session tokens and timeouts. Which one are you interested in?

**Comment by wesbragagt** [comment]
@fullykubed AWS and Vault

**Comment by fullykubed** [comment]
@wesbragagt That is controlled via AWS IAM settings, but cannot be controlled via IaC unfortunately.

Fortunately, it is easy to bump: https://docs.aws.amazon.com/singlesignon/latest/userguide/howtosessionduration.html.

12 hours is the maximum.

**Comment by fullykubed** [comment]
@wesbragagt This is the guide you are looking for: https://docs.aws.amazon.com/singlesignon/latest/userguide/configure-user-session.html#user-session-duration-how-to-configure.

We will add some reference to that in our documentation.

**Comment by fullykubed** [comment]
To clarify, this isn't controlled via IaC. It is something you need to change manually.
