### ISSUE TITLE
[question]: How should one apply to multiple AWS environments for example development and production

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#107]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

We currently have the stack bootstrapped in development/ and production/. I'm wondering what the recommendation is for running the CI system, should I apply from the development Argo workflow targeting development and production environments? Or does every environment applies its infrastructure module to itself for example in production/us-west-2/ also has a cicd_stack.

### What primary components of the stack does this relate to?

terraform, website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
@wesbragagt 

Short answer: every environment deploys its own infrastructure.

Long answer, see our architectural docs: https://panfactum.com/docs/edge/concepts/cicd/recommended-architecture.

Do those docs add clarity?

**Comment by wesbragagt** [comment]
@fullykubed Yes it makes total sense I didn't think to check that section.
