### ISSUE TITLE
[Bug]: /docs/guides/bootstrapping/preparing-aws crashes the application

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#11]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

When going to /docs/guides/bootstrapping/preparing-aws the next application crashes, seems like an issue with an image asset but takes down the whole site and any other open tabs
![Screenshot from 2024-03-10 17-04-07](https://github.com/Panfactum/stack/assets/105033689/e8bbf02d-2628-4155-ad00-7c8bbe0b3431)

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jlevydev** [comment]
This issue also appears to happen with the /docs/guides/bootstrapping/infrastructure-as-code page, different asset, but same crash
![Screenshot from 2024-03-10 17-11-06](https://github.com/Panfactum/stack/assets/105033689/71295763-cc0c-47ee-afb5-1811e78d6193)

**Comment by fullykubed** [comment]
This looks like an issue with git lfs. This repo uses git lfs for several file types including the file types you listed on this issue. See [here](https://github.com/Panfactum/stack/blob/main/.gitattributes) for the full list.

Can you share what the contents of these files currently is? Can you also share your version of git lfs and any other git configuration you have on your machine?

**Comment by jlevydev** [comment]
Looks like it was an issue with initializing git-lfs on my end. Attempted `git-lfs pull` and was instructed to run `git-lfs install` first. Ran that then pull again and the issue resolved itself. Thanks!
