### ISSUE TITLE
Loki max history is set to 5 while log retention is 14

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#112]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

Given the log retention is set to 14 days, why is the Loki max history only set to 5? Shouldn’t those values match in order for users to be able to query logs up until the log retention time?

I’m seeking to better understand those parameters so I can properly extend them for my team’s needs in terms of being able to view logs for async jobs that might’ve had a problem a week ago or so.

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Can you link to specifically what pieces of configuration you are talking about?

**Comment by wesbragagt** [comment]
@fullykubed 

* [loki.max_history](https://github.com/Panfactum/stack/blob/main/packages/infrastructure/kube_logging/main.tf#L332)
* [var.log_retention_period_hours](https://github.com/Panfactum/stack/blob/main/packages/infrastructure/kube_logging/vars.tf#L56)

**Comment by fullykubed** [comment]
The [max_history](https://github.com/Panfactum/stack/blob/c9abd4681cdaa037aa80e3e4b30b18ea4daf4b12/packages/infrastructure/kube_logging/main.tf#L332) is how many previous helm chart deployments to keep saved in the Kubernetes database. It is a generic helm parameter and not related to loki.

**Comment by wesbragagt** [comment]
@fullykubed oh ok so the log_retention_period_hours should be good enough as 14 * 24 in order to allow users to query up til then?

**Comment by fullykubed** [comment]
I believe so, but cannot make any promises as the module is still alpha quality.

**Comment by wesbragagt** [comment]
@fullykubed I totally understand! I will share any other findings I encounter.
