### ISSUE TITLE
[Bug]: error getting credentials - err - A superuser must run 'pf-update-buildkit --build' to generate

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#114]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

I was in the process of upgrading my stack from edge.24-07-08 -> edge.24-08-12 and I keep getting this error when attempting to apply on kube_karpenter. I tried deleting the .terragrunt-cache and running the recommended command. I've also verified that the buildkit folder exists.

### Steps to Reproduce

It's a bit odd to get this reproduced given you would have to be upgrading from edge.24-07-08 to edge.24-08-12.

I have a feeling it has to do with this file https://github.com/Panfactum/stack/blob/c9abd4681cdaa037aa80e3e4b30b18ea4daf4b12/packages/nix/packages/docker-credential-panfactum.sh#L34

### Relevant log output

```shell
│ Error: error getting credentials - err: exit status 1, out: `Error: /Users/wesbragagt/dev/work/implentio/infrastructure-v2/.terragrunt-cache/VNWBwD7P6on_Cx6C8vKdr5XumE0/jefY46BK7z-2whPUMHguV-9ROrg/.buildkit/buildkit.json does not exist. A superuser must run 'pf-update-buildkit --build' to generate.`
│
│   with helm_release.karpenter,
│   on main.tf line 585, in resource "helm_release" "karpenter":
│  585: resource "helm_release" "karpenter" {
│
╵
ERRO[0025] tofu invocation failed in /Users/wesbragagt/dev/work/implentio/infrastructure-v2/.terragrunt-cache/VNWBwD7P6on_Cx6C8vKdr5XumE0/jefY46BK7z-2whPUMHguV-9ROrg/packages/infrastructure/kube_karpenter  error=[/Users/wesbragagt/dev/work/implentio/infrastructure-v2/.terragrunt-cache/VNWBwD7P6on_Cx6C8vKdr5XumE0/jefY46BK7z-2whPUMHguV-9ROrg/packages/infrastructure/kube_karpenter] exit status 1 prefix=[/Users/wesbragagt/dev/work/implentio/infrastructure-v2/environments/development/us-west-2/kube_karpenter]
ERRO[0025] 1 error occurred:
        * [/Users/wesbragagt/dev/work/implentio/infrastructure-v2/.terragrunt-cache/VNWBwD7P6on_Cx6C8vKdr5XumE0/jefY46BK7z-2whPUMHguV-9ROrg/packages/infrastructure/kube_karpenter] exit status 1
```

**Comment by fullykubed** [comment]
1. Make sure you update the devenv as well.
2. Delete every .gitignored file in the buildkit directory and try again.

**Comment by wesbragagt** [comment]
@fullykubed My devenv.nix and I've deleted the .gitignore file in the buildkit directory.

```
{config, pkgs, ...}: {
  # Helps with AWS SSO login assuming different roles
  scripts.login.exec = "source $DEVENV_ROOT/scripts/aws-login.sh";

  # Helps fuzzy searching through the directories in the codebase and selecting one to change directory to
  scripts.cdl.exec = "source $DEVENV_ROOT/scripts/cdl.sh";
  scripts.deploy.exec = "bash $DEVENV_ROOT/scripts/deploy.sh";
  scripts.db-tunnel.exec = "bash $DEVENV_ROOT/scripts/db-tunnel.sh";
}
```

**Comment by fullykubed** [comment]
To clarify, don't delete the `.gitignore` file. Delete every file that is ignored by `.gitignore`.

**Comment by wesbragagt** [comment]
```*
!known_hosts
!.gitignore
!config.yaml
!config.example.yaml
!state.lock
!buildkit.json
```

is it safe to try an delete the whole buildkit folder and try again?

**Comment by wesbragagt** [comment]
@fullykubed That fixed my issue. Thank you for the help.

**Comment by fullykubed** [comment]
⚙️
