### ISSUE TITLE
[question]: aws provider error when applying karpenter_node_pools upgrade to edge.24-08-13 

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#117]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

Hi, I'm trying to upgrade my infrastructure to use edge.24-08-13 and I've followed the instructions in the changelog to upgrade kube_karpenter and kube_karpenter_node_pools but when I apply with terragrunt I'm getting the following error:

```
Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: Invalid provider configuration
│
│ Provider "registry.opentofu.org/hashicorp/aws" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: No valid credential sources found
│
│   with provider["registry.opentofu.org/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found,
│ operation error ec2imds: GetMetadata, exceeded maximum number of attempts,
│ 3, request send failed, Get
│ "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial
│ tcp 169.254.169.254:80: connect: host is down
```

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
You do not have the `aws` provider enabled. Run `pf-providers-enable` in that module directory and try again.

**Comment by wesbragagt** [comment]
@fullykubed Thank you, that worked!
