### ISSUE TITLE
[Bug]: `kube_karpenter` cannot be applied, edge.24-08-24

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#119]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

When attempting to apply the `kube_karpenter` module the apply fails when attempting to apply the helm chart with the output below. It looks like it is attempting to call `docker-credential-panfactum` somewhere under the hood within the terragrunt cache folder which is super odd to me, but I've verified that's where the error message originates from in the Panfactum code base. Let me know what other debugging information you need!

![image](https://github.com/user-attachments/assets/ad6166ab-45c0-49bf-81f8-19f43aaf43e5)

### Steps to Reproduce

1. On edge.24-08-24 attempt to apply the `kube_karpenter` module

**Comment by fullykubed** [comment]
Many helm chart publishers are starting to use [OCI-based registries](https://helm.sh/docs/topics/registries/) for their charts. This is the same registry format as for container images so it will use the same authz/n format.

Karpenter uses the public ECR registry for their charts now and if you have configured BuildKit, then `docker-credential-panfactum` will be used to fetch your credentials.

However, it looks like you may have an issue with your BuildKit configuration. Can you verify the following:

1. Do you have `buildkit_dir` set in your `panfactum.yaml`?
2. Do you have a `buildkit.json` in the `buildkit_dir` of your repo?

**Comment by jlevydev** [comment]
1. `buildkit_dir` is not set explicitly in the `panfactum.yaml` but has the correct default value when running `pf-get-repo-variables`
2. I do have a `buildkit.json` in the `buildkit_dir` and I am completing remote builds to the cluster successfully using it

Looking at the debugging output I think the root cause is that for some reason the calling directory is actually the root of the Panfactum/Stack repo within the terragrunt dir. Could that be a bug related to nesting the nix flakes and terragrunt running from within that folder? 

Let me know what else you need

**Comment by fullykubed** [comment]
Can you clear your terragrunt cache and retry?

**Comment by jlevydev** [comment]
Did that a couple times as a first step, doing it again now, still no luck :(

**Comment by fullykubed** [comment]
What is the output of running `pf-get-repo-variables | jq -r '.buildkit_dir'` inside the repo?

**Comment by fullykubed** [comment]
Can you also provide your `flake.nix` file?

**Comment by fullykubed** [comment]
Nvm. I have found the issue.

**Comment by fullykubed** [comment]
Fix is ready and will be included in the next release.
