### ISSUE TITLE
[Bug]: `host_anti_affinity_required = false` in `kube_deployment` + `kube_descheduler` lead to regular preemption 

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#123]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

I deployed a `kube_deployment` with `host_anti_affinity_required = false` to allow workloads to run on the same nodes. I immediately noticed a sharp increase in workload disruption. Upon investigation of my cluster's events I found that the `kube_descheduler` was removing duplicate pods on nodes as is the `Panfactum` default, but if that's the case it probably isn't worth having `host_anti_affinity_required` be configurable since you're basically signing up to have the `kube_descheduler` nuke a pod every five minutes lol

![image](https://github.com/user-attachments/assets/fc0ca771-c889-434e-b030-b17a2f75a50d)

### Steps to Reproduce

1. Create a `kube_deployment` with `host_anti_affinity_required = false`
2. Scale that deployment such that you have more than one pod per node in your cluster (or at least have one set of pods sharing a node)
3. Observe them get mercilessly de-scheduled

**Comment by fullykubed** [comment]
@jlevydev I verified this is an issue and it should be resolved in the next release.

**Comment by fullykubed** [comment]
Resolved.
