### ISSUE TITLE
[question]: Provisioning db user and password from dynamic vault store to workflows

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#130]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

I have an async job that I run in kubernetes and I would love to instead using the root credentials to use the vault dynamic credentials provisioning to the job. I'm looking for recommendations in the terraform modules on how to accomplish that. I've heard of vault csi provider but I'm struggling to understand how to implement that with the stack.

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Currently we do not have direct support for mounting vault secrets in pods. However, its something we were already planning on adding, so I will bump this up in priority to be included in the next release.

**Comment by fullykubed** [comment]
The code for this is completed and will be included in the next release.

**Comment by wesbragagt** [comment]
@fullykubed I just looked through the change. I'm so pumped for this addition. Thank you!
