### ISSUE TITLE
[question]: how to properly reference local panfactum stack 

### ISSUE THREAD

**Issue by uptownhr** [Panfactum/stack#132]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

Using the reference example, I've updated my repositories panfactum.url to a relative path on my local machine to the panfactum stack project. However running `nix flake update` results in the error ,

```
error:
       … while updating the lock file of flake 'git+file:///Users/james/Projects/uptownhr/alcee.click'

       … while updating the flake input 'panfactum'

       … while fetching the input 'path:../panfactum'

       error: relative path '../panfactum' points outside of its parent's store path '/nix/store/j309szlknj374xyjzql4f9gf5rhdab41-source
```

my directory structure.

projects
- panfactum
- alcee.click
  - flake.nix

from `alcee.click/flake.nix` i'm setting panfactum.url to `path:../panfactum`

### What primary components of the stack does this relate to?

reference

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
If you are referencing a flake in a different repo, you should use an absolute file system path.

**Comment by uptownhr** [comment]
Solved my problem. TY
