### ISSUE TITLE
[Bug]: Disruption window enabler error when called in namespace outside of argo

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#137]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

I've been noticing the following logs when the window enabler cronjob triggers. I also noticed this line in the relevant script https://github.com/Panfactum/stack/blob/1d9a40e6f99a92eec57c06c1012dcaea59836be5/packages/nix/packages/pf-voluntary-disruptions-enable.sh#L72 could this be an oversight when passing the namespace? 

### Steps to Reproduce

Trigger the window enabler cronjob from a different namespace

### Relevant log output

```shell
disruption-window-enabler-21ff521e416b4a5f-manual-tl7-7cgm6 enabler Error from server (Forbidden): │
│  poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:implentio:dcd00bef45311c86" │
│  cannot list resource "poddisruptionbudgets" in API group "policy" in the namespace "argo"
```

**Comment by fullykubed** [comment]
Definitely a bug! Will get it fixed in the next edge release.

**Comment by fullykubed** [comment]
Resolved.
