### ISSUE TITLE
[question]: karpenter upgrade to edge.24-08-27 failed to pull unpack image public.ecr.aws/bitnami/kubectl

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#138]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

I'm attempting to upgrade from 24-08-24 to 24-08-27 and the karpenter module creates a pod that is not able to pull the following image 
`public.ecr.aws/bitnami/kubectl:1.30@sha256:13a2ad1bd37ce42ee2a6f1ab0d30595f42eb7fe4a90d6ec848550524104a1ed6`

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wesbragagt** [comment]
@fullykubed I tried in my MacOS M1 machine: 

```shell
docker pull public.ecr.aws/bitnami/kubectl:1.30@sha256:13a2ad1bd37ce42ee2a6f1ab0d30595f42eb7fe4a90d6ec848550524104a1ed6
public.ecr.aws/bitnami/kubectl@sha256:13a2ad1bd37ce42ee2a6f1ab0d30595f42eb7fe4a90d6ec848550524104a1ed6: Pulling from bitnami/kubectl
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by wesbragagt** [comment]
I tried to put the karpenter helm version to 0.30 but I'm running into 

```│ Error: another operation (install/upgrade/rollback) is in progress
│
│   with helm_release.karpenter,
│   on main.tf line 559, in resource "helm_release" "karpenter":
```

**Comment by wesbragagt** [comment]
I was able to move forward by pinning to 0.30.0 and deleting the sh.helm.release.v1.karpenter secret that was problematic. Based on this post https://github.com/helm/helm/issues/8987

**Comment by fullykubed** [comment]
@wesbragagt Not sure what the issue there might be, but `edge.24-09-10` upgrades Karpenter to v1 and the new helm chart removes this `kubectl` image requirement entirely.

Since the issue is "fixed" in a later release, we are going to skip a deeper investigation into this.

We'd recommend that you keep the `kube_karpenter` module pinned to whatever version works for you until you reach `edge.24-09-10`.
