### ISSUE TITLE
[Bug]: terragrunt apply error on sops module

### ISSUE THREAD

**Issue by uptownhr** [Panfactum/stack#153]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

the sops (aws_kms_encrpt_key) module fail to apply during the `pf-env-

As I was bootstrapping a new aws account, the terragrunt apply for sops failed during the `pf-env-bootstrap` command

### Steps to Reproduce

1. setup new repo
2. setup dev env
3. setup iac
4. scaffold environment
5. bootstrap env with `pf-env-bootstrap`

### Relevant log output

```shell
➜  sops git:(main) ✗ terragrunt apply
INFO[0002] Downloading Terraform configurations from git::https://github.com/panfactum/stack.git?ref=8310b109f195236791bc72c6654e7a88c6f2802b into /Users/james/Projects/selflessly/infrastructure/.terragrunt-cache/KmUnHsWIwyCMjmCuEH2u1y_zH6w/jefY46BK7z-2whPUMHguV-9ROrg 
ERRO[0005] Working dir packages/infrastructure/sops from source git::https://github.com/panfactum/stack.git?ref=8310b109f195236791bc72c6654e7a88c6f2802b does not exist 
ERRO[0005] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by uptownhr** [comment]
I was able to work around by manually adding a module.yaml 

```
module: "aws_kms_encrypt_key"
providers:
  - aws
```

**Comment by fullykubed** [comment]
Fixed in next release
