### ISSUE TITLE
[Bug]: bootstrapping guide - kube_reflector fails to deploy due to scheduler not being available

### ISSUE THREAD

**Issue by uptownhr** [Panfactum/stack#157]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

During the bootstrapping guide, you are not able to deploy the kube_reflector module https://panfactum.com/docs/edge/guides/bootstrapping/certificate-management#reflector because the panfactum scheduler has not been deployed yet and guidance to turn it off is not given.

### Steps to Reproduce

1. start bootstrapping guide and get to https://panfactum.com/docs/edge/guides/bootstrapping/certificate-management#reflector
2. attempt to deploy

Notice that the pod is stuck and deployment fails
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/e5611705-8670-4474-b9a3-cc9d37463a24">

### Relevant log output

```shell
Error context deadline exceeded
```

**Comment by uptownhr** [comment]
workaround is to provide the input `panfactum_scheudler_enabled = false`

**Comment by fullykubed** [comment]
The reflector installed got moved to be earlier in the bootstrapping process so we just need to change the defaults for the module for the scheduler and vpa. Will do right now.

**Comment by fullykubed** [comment]
Fixed.
