### ISSUE TITLE
[Bug]: pf-wf-git-checkout assumes git repo ends in .git

### ISSUE THREAD

**Issue by uptownhr** [Panfactum/stack#160]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

Attempting to clone a azure git repository errors because they do not end with .git. 

Error: `fatal: repository ......git not found`

### Steps to Reproduce

1. Find a git repo hosted on azure
2. Attempt to clone using `pf-wf-git`

### Relevant log output

```shell
Example of azure git url
dev.azure.com/{org}/{project}/_git/{repo}
```

**Comment by fullykubed** [comment]
Resolved in the latest stack commit.
