### ISSUE TITLE
[feature]: wf_spec add labelsFrom default to include parameters so they are searcheable

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#169]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar request has already been made.

### What new functionality would you like to see?

In our stack it became critical to be able to identify workflows that triggered with certain parameters. In the current setup it is not possible to pass parameters as labels so they can be searched. I found [in the Argo repository examples](https://github.com/argoproj/argo-workflows/blob/main/examples/label-value-from-workflow.yaml) and I was able to add to our stack by merging the wf_spec workflowMetadata in the manifest section. 

After that I can query for workflows that triggered with a brandId=<value> for example:

![image](https://github.com/user-attachments/assets/1e1f22d3-06e7-4d05-be45-933e04c0d254)

### How would you use this new functionality?

I would love to have either a default in the wf_spec module where it spreads all the parameters as labelsFrom. Here is an example of what I had to do:

```hcl
          workflowMetadata = merge(module.workflows[key].workflow_spec.workflowMetadata, {
            # Allows us to query for input values in the Argo UI
            labelsFrom = {
              for k, v in value.parameters : v.name => {
                expression = "workflow.parameters.${v.name}"
              }
            }
          })
```

**Comment by fullykubed** [comment]
This is a good idea. Will add it to the next release.

**Comment by wesbragagt** [comment]
@fullykubed one important call out is potentially having a flag to make a parameter not searchable for instances when you have an input that is a large JSON string. I think a user should be able to turn that off for that particular parameter.

**Comment by fullykubed** [comment]
Added. Will be included in the next release.
