### ISSUE TITLE
[Bug]: Website client side exception

### ISSUE THREAD

**Issue by itzsaga** [Panfactum/stack#170]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

Website is crashing at [https://panfactum.com/stack/features](https://panfactum.com/stack/features):
![image](https://github.com/user-attachments/assets/376061ca-2e18-4298-b868-7fcf4b661708)

### Steps to Reproduce

1. Visit https://panfactum.com/stack/features
2. See error.

**Comment by fullykubed** [comment]
Good call out. Will be fixed in the upcoming website update.

**Comment by fullykubed** [comment]
Resolved in the new website
