### ISSUE TITLE
[question]: kube_monitoring metrics only showing up to 3 hours for cnpg pods

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#176]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

How can I see metric visualizations that go beyond 3 hours in the past? I'm not sure if this is an issue with the stack or the default dashboard queries.

I'm trying to analyze our kube_pg pods instances memory usage overtime and I'm noticing that when creating a time series visualization I can only go up to 3 hours back. I see that the module has a default of 15 days for `metrics_retention_resolution_raw` as described [here](https://github.com/Panfactum/stack/blob/main/packages/infrastructure/kube_monitoring/vars.tf#L139). This is the promql query I'm utilizing:

```sum(container_memory_working_set_bytes{pod=~"pg-88cc-([1-9][0-9]*)$", namespace="implentio", container!="", image!=""}) by (pod)```

I pulled the query from the CloudNativePG Dashboard provided by the stack to further explore what I could extract and noticed this.

Example where I'm trying to go 12 hours back but can only get up to much less time:

![image](https://github.com/user-attachments/assets/22ccc650-fb46-4e72-936d-590509a0d1ca)

### What primary components of the stack does this relate to?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
In the current alpha iteration of monitoring, the autoscaling isn't quite tuned. This is likely a result of monitoring pods restarting before they are able to load the entire time series. This partial result gets cached and then creates the problem you linked.

To resolve this issue, try to adjust the query slightly to invalidate the cache after scaling up any thanos pods.

**Comment by wesbragagt** [comment]
@fullykubed thank you, I was able to fix this issue by swapping the datasource to use thanos and not prometheus.
