### ISSUE TITLE
[Bug]: Authentik Forgot Password Flow - Request has been denied

### ISSUE THREAD

**Issue by uptownhr** [Panfactum/stack#177]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

Attempting to utilize the Forgot Password flow results in an error of `Request has been denied`

![image](https://github.com/user-attachments/assets/f0d1e924-eab6-4f2a-9641-d1961ec4ddae)

### Steps to Reproduce

1. go to authentik url
2. utilize the forgot password functionality
3. notice the error

**Comment by fullykubed** [comment]
Resolved in the latest commit.
