### ISSUE TITLE
[feature]: kube_pg_cluster with longer timeout for create resource

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#181]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar request has already been made.

### What new functionality would you like to see?

I would love to have a longer timeout when creating a pg cluster in order to avoid getting a tainted resource when performing [the recovery procedure](https://panfactum.com/docs/edge/reference/infrastructure-modules/submodule/kubernetes/kube_pg_cluster#recovery) with a large database.

### How would you use this new functionality?

I've implemented a [PR here](https://github.com/Panfactum/stack/pull/180) showing how we've done this in our fork of the module.

**Comment by fullykubed** [comment]
Added in the latest commit.
