### ISSUE TITLE
[feature]: Replace terraform with opentofu

### ISSUE THREAD

**Issue by fullykubed** [Panfactum/stack#20]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar request has already been made.

### What new functionality would you like to see?

With the recent changes to terraform's license, it is unclear whether using more recent versions of terraform within the Panfactum stack would violate the new licenses "embedded use" policy. It seems likely. As a result, we should migrate to opentofu once 1.7 is released.

### How would you use this new functionality?

Same as terraform

### What primary components of the stack would this impact?

terraform, nix, website, reference

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kvendingoldo** [comment]
you can also you https://github.com/tofuutils/tenv to switch between different versions of terraform/tofu

**Comment by fullykubed** [comment]
Panfactum is now on opentofu
