### ISSUE TITLE
[Bug]: Descheduler logs seem to indicate mis-configuration or missing plug-ins

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#23]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

I was investigating an unrelated issue with the Descheduler and noticed that there are some plugins that were not being loaded successfully. See logs attached below
[descheduler_plugin_issue.csv](https://github.com/Panfactum/stack/files/15213444/descheduler_plugin_issue.csv)

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Good catch! This is resolved in the latest commit.
