### ISSUE TITLE
[Bug]: MacOS pf-tunnel does not accept inputs correctly

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#25]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

We use the `pf-tunnel` command in our organization to help facilitate a "local development" environment. Using `pf-tunnel` worked on my machine however when using it on MacOS with an ARM chip one of my team members was met with the following output: 
![Screenshot 2024-05-06 at 12 30 51 PM](https://github.com/Panfactum/stack/assets/105033689/a8045613-25b3-473e-99c8-7ae0ed8d7a7c)

This output was consistent whether running `pf-tunnel` in the context of the enclosing script or vanilla in the terminal. From inspecting the script it looks like the usage block only prints when there's an error with the inputs, so wondering if there might be some difference in the argument parsing between Linux and Mac machines

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

nix

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
I have confirmed this is an issue and identified the root cause. I will be pushing an update tomorrow morning.

**Comment by fullykubed** [comment]
Resolved.
