### ISSUE TITLE
[Bug]: Devenv set up does not build when making small changes to devenv.nix

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#26]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

We are adding some custom utilities to our devenv set up. When we do so it requires reloading the shell often. However when we make small modifications we get the error seen below. I had just replaced a different custom module with the get-buildkit-address module, so the difference between the two files was only around the name. I suspect a caching issue but maybe something else. I have already tried deleting my .direnv and .devenv directories and neither has worked to resolve.

![Screenshot from 2024-05-07 10-19-33](https://github.com/Panfactum/stack/assets/105033689/0b7f1975-8d47-47a3-a0e5-ad80c4942bd8)

```nix
{ pkgs, config, inputs, ... }: 
let
  customModule = module: import ./packages/nix/${module} { pkgs = pkgs; };

  custom_packages = with pkgs; [
    (customModule "docker-credential-aws")
    (customModule "local-build")
    (customModule "sf")
    (customModule "get-buildkit-address")
    (customModule "enter-shell")
  ];
in
{
  enterShell = ''source enter-shell'';
  env = {
    PF_REPO_NAME = "hudsonts";
    PF_REPO_URL = "github.com/Hudson-Technology-Systems/hudsonts";
    PF_REPO_PRIMARY_BRANCH = "main";
    PF_ENVIRONMENTS_DIR = "environments";
    PF_IAC_DIR = "packages/terraform";
  };

  packages = custom_packages;
}
```

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

nix

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
@jlevydev Just want to quick confirm if you followed the debugging steps [here](https://panfactum.com/docs/guides/developer-environment/debugging) and are still experiencing the issue.

**Comment by fullykubed** [comment]
@jlevydev Closing this issue as resolved. Please feel free to reopen it if you are still experiencing issues.
