### ISSUE TITLE
[Bug]: pf-update-aws --build fails to apply after wiping .aws/config

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#34]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

When running `pf-update-aws --build` the script seems to clear the `.aws/config` file and then attempt to get the roles from the `aws_iam_identity_center_permissions` module with a role that no longer exists in the config file. Kind of circular. See the error below.
![image](https://github.com/Panfactum/stack/assets/105033689/368f2f72-db4f-42d6-9fee-353f5ce8c9a7)

### Steps to Reproduce

See above

### Version

main (development branch)

**Comment by fullykubed** [comment]
Resolved in the latest commit
