### ISSUE TITLE
[Bug]: tf_bootstrap_resources fails with current instructions [docs]

### ISSUE THREAD

**Issue by mschnee** [Panfactum/stack#39]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

Per [Configuring Infrastructure-as-Code](https://panfactum.com/docs/edge/guides/bootstrapping/configuring-infrastructure-as-code):
>**aws_secondary_region:** Set this to the aws_region from above.
```
# region.yaml
aws_region: us-west-2
aws_secondary_region: us-west-2
```

Causes the aws provider to throw the following error:
```
│ Error: updating Amazon DynamoDB Table (corgeek-production-state-lock-table): updating replicas, while creating: creating replica (us-west-2): ValidationException: Cannot add, delete, or update the local region through ReplicaUpdates. Use CreateTable, DeleteTable, or UpdateTable as required.
│       status code: 400, request id: L1M1VGBDCEB99I5MK47GPK9EQFVV4KQNSO5AEMVJF66Q9ASUAAJG
```

This can be remediated by changing the secondary region:
```
# region.yaml
aws_region: us-west-2
aws_secondary_region: us-east-2
```

## Suggestions
Given the importance of replicating the lock table in another region for purpose of stability and disaster recovery, it may be recommended to update the documentation to recommend setting `aws_secondary_region` to a different region, so that the lock tables and keys can be replicated.

### Steps to Reproduce

- Starting from scratch
- Create an AWS account and subaccounts
- Follow the Guides through "Configuring Infrastructure-as-Code"

### Version

main (development branch)

### Relevant log output

```shell
...
aws_s3_bucket_lifecycle_configuration.state: Creation complete after 30s [id=corgeek-production-state-bucket]
╷
│ Error: updating Amazon DynamoDB Table (corgeek-production-state-lock-table): updating replicas, while creating: creating replica (us-west-2): ValidationException: Cannot add, delete, or update the local region through ReplicaUpdates. Use CreateTable, DeleteTable, or UpdateTable as required.
│       status code: 400, request id: L1M1VGBDCEB99I5MK47GPK9EQFVV4KQNSO5AEMVJF66Q9ASUAAJG
│ 
│   with aws_dynamodb_table.lock,
│   on main.tf line 171, in resource "aws_dynamodb_table" "lock":
│  171: resource "aws_dynamodb_table" "lock" {
│ 
╵
ERRO[0046] tofu invocation failed in /home/matt/Projects/corgeek.net/stack/.terragrunt-cache/w5dThPls3tG3mqtPwds7ZROlBzU/K2rNS_bBptYOziF7qIevbc5oi_I/packages/infrastructure/tf_bootstrap_resources  prefix=[/home/matt/Projects/corgeek.net/stack/environments/production/global/tf_bootstrap_resources] 
ERRO[0046] 1 error occurred:
        * [/home/matt/Projects/corgeek.net/stack/.terragrunt-cache/w5dThPls3tG3mqtPwds7ZROlBzU/K2rNS_bBptYOziF7qIevbc5oi_I/packages/infrastructure/tf_bootstrap_resources] exit status 1
```

**Comment by fullykubed** [comment]
Good catch, and thanks for the thorough report! This was from a very old version of the stack where we allowed modules to deploy to multiple accounts. However, in all current versions of the stack, the documentation is straight up incorrect here, and we even have different values in our reference repo. I have adjusted it in all guide versions in the latest commit.
