### ISSUE TITLE
[feature]: aws_registered_domains contact phone format needs validation

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#43]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar request has already been made.

### What new functionality would you like to see?

In the DNS Setup - https://panfactum.com/docs/24-05/guides/bootstrapping/dns#user-content-fn-1, if there are any mismatches between domain contact information such as PHONE formats 999-1234 vs +999.1234(format used by AWS) it will fail when running apply. A terraform validation rule would help here.

## AWS Docs
https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_ContactDetail.html

### How would you use this new functionality?

When going through the guided setup, it's not clear what the contact phone number format should be so I'd assume folks would face this issue if they are using a common format 999-1234 as oppose to what AWS requires +999.1234. I think this would help clarify any confusions and time debugging.

## Pull-Request with Proposed Feature
https://github.com/Panfactum/stack/pull/44

**Comment by fullykubed** [comment]
Added in #44
