### ISSUE TITLE
[feature]: `aws_ses_domain` security

### ISSUE THREAD

**Issue by mschnee** [Panfactum/stack#51]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar request has already been made.

### What new functionality would you like to see?

The IAM user needs to be locked down:
- IP Blocks to ensure it's only used by the cluster and cannot be exfiltrated.

### How would you use this new functionality?

Keep the SMTP auth locked down so that it cannot be exposed.

**Comment by fullykubed** [comment]
Added.
