### ISSUE TITLE
[Bug]:  The dotenv file '.env' was not found after updating to edge.24-06-2

### ISSUE THREAD

**Issue by mschnee** [Panfactum/stack#52]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

At some point between `2048c3439e17a497a947495129639c8b38d4a6b9` (edge.2024-05-23) and `58b63910959cf791b313f836236ecdbefd2bc644` (edge.2024-06-02), the nix flake was no longer able to find the correct path for `$DEVENT_ROOT/.env` 

This renders the `.env` file nonoperative and any functionality depending on it, e.g. `VAULT_ADDR`, `VAULT_TOKEN`, `AWS_PROFILE` is broken because these values are now `@INVALID@` or unset.

### Steps to Reproduce

`nix flake update`

### Version

main (development branch)

### Relevant log output

```shell
❯ direnv reload
direnv: loading ~/Projects/corgeek.net/stack/.envrc
direnv: loading https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.4/direnvrc (sha256-DzlYZ33mWF/Gs8DDeyjr8mnVmQGx7ASYqA5WlxwvBG4=)
direnv: using flake . --impure
warning: Git tree '/home/matt/Projects/corgeek.net/stack' is dirty
evaluating derivation 'git+file:///home/matt/Projects/corgeek.net/stack#devShells.x86_64-linux.default'direnv: ([direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
warning: Git tree '/home/matt/Projects/corgeek.net/stack' is dirty
direnv: nix-direnv: renewed cache
💡 The dotenv file '.env' was not found.
```

**Comment by mschnee** [comment]
This may be the cause:
https://github.com/Panfactum/stack/compare/edge.24-05-23...edge.24-06-02#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0L9

Per the devenv github, this is a **wontfix** because of the usage of nix flakes: https://github.com/cachix/devenv/issues/1135#issuecomment-2127681361

They instead recommend doing something in `enterShell` instead.  One recipient is using `nodePackages.dotnet-cli` to do this.

**Comment by mschnee** [comment]
Seems the solution might be to update `.envrc` to include
```emv
dotenv_if_exists .env
```

**Comment by fullykubed** [comment]
I need to look into this further. Loading `.env` into the shell environment is only 1/2 the battle.

The expectations is that these values actually parameterize devenv itself to build in different ways (e.g., with `CI` as `true` vs `false`). Nix will not have access to environment variables.

**Comment by mschnee** [comment]
This is a silly question, but would this work? 
```envrc
dotenv_if_exists .env

if ! use flake . --impure; then
  echo "devenv could not be built. The devenv environment was not loaded. Make the necessary changes to devenv.nix and hit enter to try again." >&2
fi
```

**Comment by fullykubed** [comment]
Unfortunately, no. 

Nix cannot access environment variables as this breaks its concept of being completely derived from source code files. `.env` was allowed as it was a file. 

Ultimately, I wasn't able to find a fix without introducing some ugly hacks, so I accepted your solution in your PR with some additional changes.

This will complicate things for my CI work, but that is a problem for future Jack. Right now, I agree that getting `.env` files working is a priority.
