### ISSUE TITLE
[feature]: UX - app -> vault -> authentik requires user to select OIDC at the Vault Login page

### ISSUE THREAD

**Issue by mschnee** [Panfactum/stack#59]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar request has already been made.

### What new functionality would you like to see?

When setting up a client/provider via `vault_identity_oidc_provider` and `vault_identity_oidc_client`, an OIDC redirect from a webapp takes the user to Vault, where they are required to "Log into vault with your credentials".  By default, the "token" option is selected.

Currently, the user has to be instructed to "select OIDC from the Method Drop-down, do not enter a role, and click Sign in with OIDC Provider".

A better UX would be to just pass through vault transparently as if there were no other options to choose.  I am unsure if this is possible. 

### How would you use this new functionality?

Using Vault -> Authentik for user log-in is currently not a great experience, as it requires providing additional instruction to end-user even though there is _no other mechanism available_.

**Comment by fullykubed** [comment]
Can you please try to the latest edge release and validate that this is still the behavior?

**Comment by fullykubed** [comment]
@mschnee Just want to confirm this was resolved for you before I close it.

**Comment by mschnee** [comment]
Will check tomorrow!  We have the day off today so the lady and I are doing wedding prep.

**Comment by fullykubed** [comment]
Resolved.
