### ISSUE TITLE
[Bug]: Authentik SSO Application Dashboard Missing Logos

### ISSUE THREAD

**Issue by wesbragagt** [Panfactum/stack#66]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

The SSO app's logos in the user's dashboard all show as coming from `/media/public/media/public/aws-ba0983012a81e316.svg` instead the configured source which should be `/media/public/aws-ba0983012a81e316.svg `

![image](https://github.com/Panfactum/stack/assets/40429790/38c6ddb6-5e95-4944-867a-321c09126d93)

### Steps to Reproduce

Sign-in Authentik and look at the user's dashboard list of apps.

### Version

main (development branch)

**Comment by fullykubed** [comment]
Resolved. Will be included in the next release.
