### ISSUE TITLE
[Bug]: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/0.37.0: 403 Forbidden

### ISSUE THREAD

**Issue by mschnee** [Panfactum/stack#70]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

Attempting to update `kube_karpenter` from `989fdf29d21baaffd355ad9faf599e313a5eda3e` to `edge.24-07-1` and `terraform apply` results in this failure.  `pf-update` was run and `./.buildkit` was set up with `pf-update-buildkit --build`

I was able to remediate in the short term by :
- remove `.credHelpers['public.ecr.aws` from `./.buildkit/config.json`
- running `aws ecr-public get-login-password --region us-east-1 | podman login --username AWS --password-stdin public.ecr.aws`

NOTE: attempting to use the above `get-login-password` line without modifying the `config.json` to remove `panfactum` as the credential helper results in the error `Error: The Panfactum credential helper can only be used for ECR registries`

My assumption is that `docker-crtedential-panfactum` may have a bug with `if TOKEN=$(get_saved_token)`, where it is loading something either invalid or incorrect.  I'm not sure if `aws ecr-public get-login-password` and `aws ecr get-login-password` result in different tokens which are not interchangable.

### Steps to Reproduce

- Update pf_stack_version to `edge.24-07-01`
- Delete the cache ad `rm -rf ./.terragrunt-cache`
- `cd config/development/us-west-2/kube_karpenter`
- Attempt to `terragrunt apply`

### Version

main (development branch)

### Relevant log output

```shell
╷
│ Error: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/0.37.0: 403 Forbidden
│
│   with helm_release.karpenter,
│   on main.tf line 584, in resource "helm_release" "karpenter":
│  584: resource "helm_release" "karpenter" {
│
╵
ERRO[0015] tofu invocation failed in /home/matt/Projects/corgeek.net/stack/.terragrunt-cache/TKqzO8_al28OwDeZ2JEDWE3yWQA/jefY46BK7z-2whPUMHguV-9ROrg/packages/infrastructure/kube_karpenter  error=[/home/matt/Projects/corgeek.net/stack/.terragrunt-cache/TKqzO8_al28OwDeZ2JEDWE3yWQA/jefY46BK7z-2whPUMHguV-9ROrg/packages/infrastructure/kube_karpenter] exit status 1 prefix=[/home/matt/Projects/corgeek.net/stack/IaC/config/development/us-west-2/kube_karpenter]
ERRO[0015] 1 error occurred:
        * [/home/matt/Projects/corgeek.net/stack/.terragrunt-cache/TKqzO8_al28OwDeZ2JEDWE3yWQA/jefY46BK7z-2whPUMHguV-9ROrg/packages/infrastructure/kube_karpenter] exit status 1
```

**Comment by fullykubed** [comment]
This issue is already resolved in `main` and will be included in the next edge release.
