### ISSUE TITLE
[question]: Karpenter EKS Node Capacity Utilization

### ISSUE THREAD

**Issue by uptownhr** [Panfactum/stack#90]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a similar question has already been asked.

### What is your question?

After the Panfactum Bootstrap guide, I checked my cost and node utilization and found, 

1. cost to be around $8.50 a day ($250 a mont)
2. the spot nodes are greatly over provisioned (had around 12g available of 24g)
3. attempting to cancel spot reservations only recreated them 

<img width="988" alt="image" src="https://github.com/user-attachments/assets/335aa5c9-cee0-45bf-b63c-19e6f79c789f">

Is it expected to over provision by 50%? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
Do you have `enhanced_ha_enabled` set to `true` or `false`?

**Comment by uptownhr** [comment]
> enhanced_ha_enabled

this is currently set to `false` for the region

**Comment by fullykubed** [comment]
It should be set to `false` for optimal savings. Enabling enhanced HA requires more nodes to effectively spread workloads across AZs.

**Comment by fullykubed** [comment]
Can you provide the metrics without the `-a` flag? The `-a` flag does not provide the correct utilization metrics.

**Comment by fullykubed** [comment]
However, a single point-in-time capture like this isn't going to tell you very much about the actual efficiency of the cluster.

There are many things that could lead to a temporary over-provisioning: 

- Node churn
- Unavailability of smaller spot instances in your region
- PDBs blocking disruption

Our target is that resource requests / node resources should be roughly 80% over a week long time period. The actual cost of that tends to be ~$200 / month for your first production cluster (including Authentik). However, pricing can vary dramatically somewhat depending on both (1) AWS instance pricing  and (2) instance availability, both of which are region _and_ time-specific.

**Comment by uptownhr** [comment]
Waited a day and see a small decrease in cost but utilization remains the same.

<img width="989" alt="image" src="https://github.com/user-attachments/assets/6b1f2688-ce06-4fe4-9e47-33c2aa992eb2">

**Comment by fullykubed** [comment]
Ok. So to get back to your question:

> Is it expected to over provision by 50%?

The answer to this is **no** as long as the following circumstances are met for _all_ modules:

- `enhanced_ha_enabled` is `false`
- `vpa_enabled` is `true`
- `panfactum_scheduler_enabled` is `true`
- you have not deployed anything that is not a Panfactum module

I have verified >75% utilization in the reference cluster using the latest release.

So if you are experiencing over-provisioning to this extent, this is a sign that something has gone wrong. With the given information, it is impossible to say exactly what.

More than that, point-in-time metrics like you have provided really cannot paint an accurate picture of the utilization. Given that you are at around $250 / month for _everything_ (not just the cluster), I think your average utilization is likely higher than you think, just not at the moment when you measured it.

In the future, we will create a cost optimization guide that users can use to guide them through their debugging experience.

Additionally, our soon-to-be-released monitoring stack will be able to paint a more accurate picture of your actual utilization numbers.
